import { z } from "zod";
export declare const createProjectSchema: z.ZodObject<{
    name: z.ZodString;
    hasUxTeam: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    name: string;
    hasUxTeam: boolean;
}, {
    name: string;
    hasUxTeam?: boolean | undefined;
}>;
export declare const updateProjectSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    hasUxTeam: z.ZodOptional<z.ZodBoolean>;
    dbgaContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    specContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    architectureContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    useCasesContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    userStoriesContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    mddContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    blueprintContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    tasksContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    apiContractsContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    logicFlowsContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    infraContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    uxUiGuideContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    phase0SummaryContent: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    figmaMapping: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    hasUxTeam?: boolean | undefined;
    figmaMapping?: Record<string, unknown> | null | undefined;
    dbgaContent?: string | null | undefined;
    specContent?: string | null | undefined;
    architectureContent?: string | null | undefined;
    useCasesContent?: string | null | undefined;
    userStoriesContent?: string | null | undefined;
    mddContent?: string | null | undefined;
    blueprintContent?: string | null | undefined;
    tasksContent?: string | null | undefined;
    apiContractsContent?: string | null | undefined;
    logicFlowsContent?: string | null | undefined;
    infraContent?: string | null | undefined;
    uxUiGuideContent?: string | null | undefined;
    phase0SummaryContent?: string | null | undefined;
}, {
    name?: string | undefined;
    hasUxTeam?: boolean | undefined;
    figmaMapping?: Record<string, unknown> | null | undefined;
    dbgaContent?: string | null | undefined;
    specContent?: string | null | undefined;
    architectureContent?: string | null | undefined;
    useCasesContent?: string | null | undefined;
    userStoriesContent?: string | null | undefined;
    mddContent?: string | null | undefined;
    blueprintContent?: string | null | undefined;
    tasksContent?: string | null | undefined;
    apiContractsContent?: string | null | undefined;
    logicFlowsContent?: string | null | undefined;
    infraContent?: string | null | undefined;
    uxUiGuideContent?: string | null | undefined;
    phase0SummaryContent?: string | null | undefined;
}>;
export declare const phase0DeepResearchBodySchema: z.ZodObject<{
    userIdea: z.ZodOptional<z.ZodString>;
    urls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    includeBenchmark: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    includeBenchmark: boolean;
    userIdea?: string | undefined;
    urls?: string[] | undefined;
}, {
    userIdea?: string | undefined;
    urls?: string[] | undefined;
    includeBenchmark?: boolean | undefined;
}>;
export declare const projectResponseSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    hasUxTeam: z.ZodBoolean;
    status: z.ZodEnum<["ROJO", "AMARILLO", "VERDE"]>;
    precisionScore: z.ZodNumber;
    dbgaContent: z.ZodNullable<z.ZodString>;
    specContent: z.ZodNullable<z.ZodString>;
    architectureContent: z.ZodNullable<z.ZodString>;
    useCasesContent: z.ZodNullable<z.ZodString>;
    userStoriesContent: z.ZodNullable<z.ZodString>;
    mddContent: z.ZodNullable<z.ZodString>;
    blueprintContent: z.ZodNullable<z.ZodString>;
    tasksContent: z.ZodNullable<z.ZodString>;
    apiContractsContent: z.ZodNullable<z.ZodString>;
    logicFlowsContent: z.ZodNullable<z.ZodString>;
    infraContent: z.ZodNullable<z.ZodString>;
    uxUiGuideContent: z.ZodNullable<z.ZodString>;
    phase0SummaryContent: z.ZodNullable<z.ZodString>;
    figmaMapping: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    createdAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    hasUxTeam: boolean;
    status: "ROJO" | "AMARILLO" | "VERDE";
    precisionScore: number;
    figmaMapping: Record<string, unknown> | null;
    dbgaContent: string | null;
    specContent: string | null;
    architectureContent: string | null;
    useCasesContent: string | null;
    userStoriesContent: string | null;
    mddContent: string | null;
    blueprintContent: string | null;
    tasksContent: string | null;
    apiContractsContent: string | null;
    logicFlowsContent: string | null;
    infraContent: string | null;
    uxUiGuideContent: string | null;
    phase0SummaryContent: string | null;
    createdAt: string;
}, {
    id: string;
    name: string;
    hasUxTeam: boolean;
    status: "ROJO" | "AMARILLO" | "VERDE";
    precisionScore: number;
    figmaMapping: Record<string, unknown> | null;
    dbgaContent: string | null;
    specContent: string | null;
    architectureContent: string | null;
    useCasesContent: string | null;
    userStoriesContent: string | null;
    mddContent: string | null;
    blueprintContent: string | null;
    tasksContent: string | null;
    apiContractsContent: string | null;
    logicFlowsContent: string | null;
    infraContent: string | null;
    uxUiGuideContent: string | null;
    phase0SummaryContent: string | null;
    createdAt: string;
}>;
export type Phase0DeepResearchBody = z.infer<typeof phase0DeepResearchBodySchema>;
export type CreateProjectDto = z.infer<typeof createProjectSchema>;
export type UpdateProjectDto = z.infer<typeof updateProjectSchema>;
export type ProjectResponse = z.infer<typeof projectResponseSchema>;
